[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
    "cd frontend && npm install && npm run build",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"