# Railway.app konfigurációs fájl

# Python verzió
python_version = "3.11"

# Build parancsok
[build]
build_command = "chmod +x build.sh && ./build.sh"

# Start parancs
[start]
start_command = "cd backend && python3 manage.py collectstatic --noinput && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

# Környezeti változók
[env]
DJANGO_SETTINGS_MODULE = "config.settings_production"
DEBUG = "False"
SECRET_KEY = "railway-secret-key-change-in-production"
ALLOWED_HOSTS = "*.railway.app,your-domain.com"

# Port beállítás
PORT = "8000"
