# Railway.app konfigurációs fájl

# Python verzió
python_version = "3.11"

# Build parancsok
[build]
build_command = "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"

# Start parancs
[start]
start_command = "cd backend && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

# Környezeti változók
[env]
DJANGO_SETTINGS_MODULE = "config.settings_production"
DEBUG = "False"
SECRET_KEY = "railway-secret-key-change-in-production"
ALLOWED_HOSTS = "*.railway.app,your-domain.com"

# Port beállítás
PORT = "8000"
