# Generated by Django 5.2.6 on 2025-09-06 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Halloween Kincskereső', max_length=100)),
                ('status', models.CharField(choices=[('setup', 'Beállítás'), ('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('finished', 'Befejezve')], default='setup', max_length=20)),
                ('meeting_station', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('phase', models.CharField(choices=[('separate', 'Külön Fázis'), ('together', 'Közös Fázis')], max_length=20)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(blank=True, choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('help_text', models.TextField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='treasurehunt.station')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat')], max_length=20)),
                ('current_station', models.IntegerField(default=1)),
                ('attempts', models.IntegerField(default=0)),
                ('help_used', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='treasurehunt.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='treasurehunt.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('attempts_made', models.IntegerField(default=1)),
                ('help_used', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.game')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.station')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.team')),
            ],
            options={
                'unique_together': {('game', 'team', 'station')},
            },
        ),
    ]
