# Generated by Django 5.2.3 on 2025-09-08 17:00

from django.db import migrations, models
import random
import string


def generate_game_codes(apps, schema_editor):
    """Meglévő játékokhoz egyedi kódok generálása"""
    Game = apps.get_model('treasurehunt', 'Game')
    
    for game in Game.objects.all():
        # Egyedi kód generálása
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            if not Game.objects.filter(game_code=code).exists():
                game.game_code = code
                game.save()
                break


def reverse_generate_game_codes(apps, schema_editor):
    """Visszavonás - nincs szükség"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.CharField(blank=True, help_text='Admin neve aki létrehozta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(help_text='Rövid azonosító a játékhoz csatlakozáshoz', max_length=8, null=True),
        ),
        migrations.RunPython(generate_game_codes, reverse_generate_game_codes),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(help_text='Rövid azonosító a játékhoz csatlakozáshoz', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Várakozás játékosokra'), ('setup', 'Beállítás'), ('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('finished', 'Befejezve')], default='waiting', max_length=20),
        ),
    ]
