# Generated by Django 5.2.3 on 2025-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_game_created_by_game_game_code_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='qr_code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='team_type',
            field=models.CharField(blank=True, choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(db_index=True, help_text='Rövid azonosító a játékhoz csatlakozáshoz', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Várakozás játékosokra'), ('setup', 'Beállítás'), ('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('finished', 'Befejezve')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='phase',
            field=models.CharField(choices=[('separate', 'Külön Fázis'), ('together', 'Közös Fázis')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_station',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat')], db_index=True, max_length=20),
        ),
    ]
