# Generated by Django 5.2.3 on 2025-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='team_type',
            field=models.CharField(blank=True, choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat'), ('both', '🤝 Mindkét Csapat'), (None, 'Közös Feladat')], db_index=True, max_length=20, null=True),
        ),
    ]
