# Generated by Django 5.2.3 on 2025-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_alter_challenge_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_penalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='penalty_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
