# Generated by Django 5.2.3 on 2025-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_team_is_penalized_team_penalty_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='phase',
            field=models.CharField(choices=[('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('penalty', 'Büntetés Fázis')], db_index=True, max_length=20),
        ),
    ]
