# Generated by Django 5.2.3 on 2025-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0006_alter_station_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='penalty_from_station',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
