# Generated by Django 5.2.3 on 2025-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0007_team_penalty_from_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='separate_phase_save_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='together_phase_save_used',
            field=models.BooleanField(default=False),
        ),
    ]
