# Generated by Django 5.2.3 on 2025-09-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0008_add_save_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='phase',
            field=models.CharField(choices=[('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('meeting', 'Találkozási Pont'), ('save', 'Mentesítő Fázis'), ('penalty', 'Büntetés Fázis')], db_index=True, max_length=20),
        ),
    ]
