# Generated by Django 5.2.3 on 2025-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0009_add_save_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_penalized',
        ),
        migrations.RemoveField(
            model_name='team',
            name='penalty_attempts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='penalty_from_station',
        ),
        migrations.AlterField(
            model_name='station',
            name='phase',
            field=models.CharField(choices=[('separate', 'Külön Fázis'), ('together', 'Közös Fázis'), ('meeting', 'Találkozási Pont'), ('save', 'Mentesítő Fázis')], db_index=True, max_length=20),
        ),
    ]
