# Generated by Django 5.2.3 on 2025-09-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0010_remove_penalty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='token_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
