# Generated by Django 5.2.6 on 2025-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0011_add_session_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
