# Generated by Django 5.2.6 on 2025-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0012_player_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(choices=[(1, '1 játékos'), (2, '2 játékos'), (3, '3 játékos'), (4, '4 játékos'), (5, '5 játékos'), (6, '6 játékos'), (7, '7 játékos'), (8, '8 játékos')], default=4, help_text='Maximum játékosok száma'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_count',
            field=models.PositiveIntegerField(choices=[(1, '1 csapat'), (2, '2 csapat')], default=2, help_text='Csapatok száma'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.PositiveIntegerField(default=2, help_text='Maximum játékosok száma ebben a csapatban'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('pumpkin', '🎃 Tök Csapat'), ('ghost', '👻 Szellem Csapat'), ('main', '🎮 Főcsapat')], db_index=True, max_length=20),
        ),
    ]
